-*- mode: org; org-confirm-babel-evaluate: nil -*-
* Ignore everything and add specific things back
#+begin_src text :tangle .gitignore
  # Ignore everything
  ,*
  # Include README.org
  !README.org
#+end_src
References:
- https://jasonstitt.com/gitignore-whitelisting-patterns
* Store customization information in a separate file
By default Emacs uses the ~user-init-file~ for storing customization
information. Unfortunately I regenerate the same file whenever I
update the Emacs configuration by tangling the file you are currently
reading, erasing the customization information. Therefore I store it
in a separate file which is only written by Emacs itself. Then I tell
Emacs to load it and not to be mad if it does not exist.
#+begin_src elisp :tangle init.el
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (load custom-file t) ;; Load custom file reporting no error if it does not exist.
#+end_src
* Make backup files in dedicated directory
#+begin_src elisp :tangle init.el
  (setq backup-directory-alist `(("." . ,(expand-file-name "backup" user-emacs-directory))))
#+end_src
* Disable lockfiles
#+begin_src elisp :tangle init.el
  (setq create-lockfiles nil)
#+end_src
* Install Elpaca
[[https://github.com/progfolio/elpaca][Elpaca]] is a package manager for Emacs.
#+begin_src elisp :tangle init.el
  (defvar elpaca-installer-version 0.6)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
				:ref nil
				:files (:defaults "elpaca-test.el" (:exclude "extensions"))
				:build (:not elpaca--activate-package)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
	 (build (expand-file-name "elpaca/" elpaca-builds-directory))
	 (order (cdr elpaca-order))
	 (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (< emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
	  (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
		   ((zerop (call-process "git" nil buffer t "clone"
					 (plist-get order :repo) repo)))
		   ((zerop (call-process "git" nil buffer t "checkout"
					 (or (plist-get order :ref) "--"))))
		   (emacs (concat invocation-directory invocation-name))
		   ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
					 "--eval" "(byte-recompile-directory \".\" 0 'force)")))
		   ((require 'elpaca))
		   ((elpaca-generate-autoloads "elpaca" repo)))
	      (progn (message "%s" (buffer-string)) (kill-buffer buffer))
	    (error "%s" (with-current-buffer buffer (buffer-string))))
	((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (load "./elpaca-autoloads")))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))
#+end_src
#+begin_src elisp :tangle early-init.el
  (setq package-enable-at-startup nil)
#+end_src
#+begin_src elisp :tangle init.el
  ;; Install use-package support
  (elpaca elpaca-use-package
	  ;; Enable :elpaca use-package keyword.
	  (elpaca-use-package-mode)
	  ;; Assume :elpaca t unless otherwise specified.
	  (setq elpaca-use-package-by-default t))

  ;; Block until current queue processed.
  (elpaca-wait)
#+end_src
* Install Magit
#+begin_src elisp :tangle init.el
  (use-package magit
    :config
    ;; Refresh the status buffer of the current repository after a buffer is saved to its file.
    (add-hook 'after-save-hook 'magit-after-save-refresh-status t))
#+end_src
* Install Diff-Hl-Mode
[[https://github.com/dgutov/diff-hl][Diff-Hl-Mode]] highlights uncommitted changes on the left side of the
window, allows to jump between and revert them selectively.
#+begin_src elisp :tangle init.el
  (use-package diff-hl
    :hook
    ((org-mode prog-mode) . diff-hl-mode)
    (magit-pre-refresh-hook . diff-hl-magit-pre-refresh)
    (magit-post-refresh . diff-hl-magit-post-refresh)
    :config
    ;; Perform highlighting on-the-fly.
    (diff-hl-flydiff-mode t))
#+end_src
* Load support for language on execution of code block
#+begin_src elisp :tangle init.el
  (defadvice org-babel-execute-src-block (around load-language nil activate)
    "Load language if needed"
    (let ((language (org-element-property :language (org-element-at-point))))
      (unless (cdr (assoc (intern language) org-babel-load-languages))
	(add-to-list 'org-babel-load-languages (cons (intern language) t))
	(org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages))
      ad-do-it))
#+end_src
Source: https://emacs.stackexchange.com/a/20618
* Ensure environment variables look the same as in the user's shell
#+begin_src elisp :tangle init.el
  (use-package exec-path-from-shell
    :config
    (exec-path-from-shell-initialize))
#+end_src
* Android configuration
** The configuration script
:PROPERTIES:
:header-args: :tangle (if (getenv "TERMUX_VERSION") "no" "configure-termux") :results none 
:END:
*** Deliberately cause the configuration script to fail
#+begin_src shell
  set -euxo pipefail
#+end_src
*** Select mirror or mirror group
#+begin_src shell
  : "Did I select either a mirror or a mirror group?"
  if [ ! -f .termux-change-repo ]; then
      termux-change-repo
      touch .termux-change-repo
  fi
#+end_src
*** Update apt databases from configured repositories
We update apt databases at most once a week as suggested [[https://wiki.termux.com/wiki/Package_Management][here]].
#+begin_src shell
  : "Did I update the apt databases in the last week?"
  if [ ! -f .pkg-update ] || [[ $(find . -name ".pkg-update" -mtime +7 -print) ]]; then
      pkg update -y
      touch .pkg-update
  fi
#+end_src
References:
- https://stackoverflow.com/a/32019461
- https://wiki.termux.com/wiki/Package_Management
*** Upgrade all installed packages to the latest version
#+begin_src shell
  : "Did I upgrade all the installed packages?"
  if [ ! -f .pkg-upgrade ]; then
      pkg upgrade -y
      touch .pkg-upgrade
  fi
#+end_src
*** Enable the ~x11-repo~ repository
#+begin_src shell
  : "Did I enable the x11-repo repository?"
  if [ ! -f .x11-repo ]; then
      pkg install x11-repo
      touch .x11-repo
  fi
#+end_src
References:
- https://github.com/termux/termux-x11
*** Install the nighly companion package
#+begin_src shell
  : "Did I install the companion package?"
  if [ ! -f .pkg-install-termux-x11-nightly ]; then
      pkg install termux-x11-nightly -y
      touch .pkg-install-termux-x11-nightly
  fi
#+end_src
*** Install Git
#+begin_src shell
  : "Did I install Git?"
  if [ ! -f .pkg-install-git ]; then
      pkg install git -y
      touch .pkg-install-git
  fi
#+end_src
*** Install Emacs
#+begin_src shell
  : "Did I install Emacs?"
  if [ ! -f .pkg-install-emacs ]; then
      pkg install emacs-x -y
      touch .pkg-install-emacs
  fi
#+end_src
*** Clone this repository
#+begin_src shell
  : "Did I clone the Emacs configuration repository?"
  if [ ! -d .emacs.d ]; then
      git clone https://github.com/gscatto/.emacs.d.git
  fi
#+end_src
*** Generate the configuration files
#+begin_src shell
  : "Regenerate the configuration files"
  (cd .emacs.d && emacs --batch -Q -l org README.org -f org-babel-tangle)
#+end_src
** Remote configuration process
*** Send the configuration script to the terminal
#+begin_src shell :results silent
  cat configure-termux | curl -T - https://ppng.io/kj1q98cnj12
#+end_src
*** Receive and execute the configuration script at the terminal
#+begin_src shell :results none
  bash <(curl https://ppng.io/kj1q98cnj12)
#+end_src
