-*- mode: org; org-confirm-babel-evaluate: nil -*-
* Ignore everything and add specific things back
#+begin_src text :tangle .gitignore
  # Ignore everything
  ,*
  # Include README.org
  !README.org
#+end_src
References:
- https://jasonstitt.com/gitignore-whitelisting-patterns
* Store customization information in a separate file
By default Emacs uses the ~user-init-file~ for storing customization
information. Unfortunately I regenerate the same file whenever I
update the Emacs configuration by tangling the file you are currently
reading, erasing the customization information. Therefore I store it
in a separate file which is only written by Emacs itself. Then I tell
Emacs to load it and not to be mad if it does not exist.
#+begin_src elisp :tangle init.el
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (load custom-file t) ;; Load custom file reporting no error if it does not exist.
#+end_src
* Make backup files in dedicated directory
#+begin_src elisp :tangle init.el
  (setq backup-directory-alist `(("." . ,(expand-file-name "backup" user-emacs-directory))))
#+end_src
* Disable lockfiles
#+begin_src elisp :tangle init.el
  (setq create-lockfiles nil)
#+end_src
* Install Elpaca
[[https://github.com/progfolio/elpaca][Elpaca]] is a package manager for Emacs.
#+begin_src elisp :tangle init.el
  (defvar elpaca-installer-version 0.6)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
				:ref nil
				:files (:defaults "elpaca-test.el" (:exclude "extensions"))
				:build (:not elpaca--activate-package)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
	 (build (expand-file-name "elpaca/" elpaca-builds-directory))
	 (order (cdr elpaca-order))
	 (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (< emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
	  (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
		   ((zerop (call-process "git" nil buffer t "clone"
					 (plist-get order :repo) repo)))
		   ((zerop (call-process "git" nil buffer t "checkout"
					 (or (plist-get order :ref) "--"))))
		   (emacs (concat invocation-directory invocation-name))
		   ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
					 "--eval" "(byte-recompile-directory \".\" 0 'force)")))
		   ((require 'elpaca))
		   ((elpaca-generate-autoloads "elpaca" repo)))
	      (progn (message "%s" (buffer-string)) (kill-buffer buffer))
	    (error "%s" (with-current-buffer buffer (buffer-string))))
	((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (load "./elpaca-autoloads")))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))
#+end_src
#+begin_src elisp :tangle early-init.el
  (setq package-enable-at-startup nil)
#+end_src
#+begin_src elisp :tangle init.el
  ;; Install use-package support
  (elpaca elpaca-use-package
	  ;; Enable :elpaca use-package keyword.
	  (elpaca-use-package-mode)
	  ;; Assume :elpaca t unless otherwise specified.
	  (setq elpaca-use-package-by-default t))

  ;; Block until current queue processed.
  (elpaca-wait)
#+end_src
* Install Magit
#+begin_src elisp :tangle init.el
  (use-package magit
    :config
    ;; Refresh the status buffer of the current repository after a buffer is saved to its file.
    (add-hook 'after-save-hook 'magit-after-save-refresh-status t))
#+end_src
* Install Diff-Hl-Mode
[[https://github.com/dgutov/diff-hl][Diff-Hl-Mode]] highlights uncommitted changes on the left side of the
window, allows to jump between and revert them selectively.
#+begin_src elisp :tangle init.el
  (use-package diff-hl
    :hook
    ((org-mode prog-mode) . diff-hl-mode)
    (magit-pre-refresh-hook . diff-hl-magit-pre-refresh)
    (magit-post-refresh . diff-hl-magit-post-refresh)
    :config
    ;; Perform highlighting on-the-fly.
    (diff-hl-flydiff-mode t))
#+end_src
* Load support for language on execution of code block
#+begin_src elisp :tangle init.el
  (defadvice org-babel-execute-src-block (around load-language nil activate)
    "Load language if needed"
    (let ((language (org-element-property :language (org-element-at-point))))
      (unless (cdr (assoc (intern language) org-babel-load-languages))
	(add-to-list 'org-babel-load-languages (cons (intern language) t))
	(org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages))
      ad-do-it))
#+end_src
Source: https://emacs.stackexchange.com/a/20618
