-*- mode: org; org-confirm-babel-evaluate: nil -*-
* Emacs configuration
** Ignore everything and add specific things back
#+begin_src text :tangle .gitignore
  # Ignore everything
  ,*
  # Include README.org
  !README.org
#+end_src
References:
- https://jasonstitt.com/gitignore-whitelisting-patterns
** Store customization information in a separate file
By default Emacs uses the ~user-init-file~ for storing customization
information. Unfortunately I regenerate the same file whenever I
update the Emacs configuration by tangling the file you are currently
reading, erasing the customization information. Therefore I store it
in a separate file which is only written by Emacs itself. Then I tell
Emacs to load it and not to be mad if it does not exist.
#+begin_src elisp :tangle init.el
  (setq custom-file (expand-file-name "custom.el" user-emacs-directory))
  (load custom-file t) ;; Load custom file reporting no error if it does not exist.
#+end_src
** Make backup files in dedicated directory
#+begin_src elisp :tangle init.el
  (setq backup-directory-alist `(("." . ,(expand-file-name "backup" user-emacs-directory))))
#+end_src
** Disable lockfiles
#+begin_src elisp :tangle init.el
  (setq create-lockfiles nil)
#+end_src
** Install Elpaca
[[https://github.com/progfolio/elpaca][Elpaca]] is a package manager for Emacs.
#+begin_src elisp :tangle init.el
  (defvar elpaca-installer-version 0.6)
  (defvar elpaca-directory (expand-file-name "elpaca/" user-emacs-directory))
  (defvar elpaca-builds-directory (expand-file-name "builds/" elpaca-directory))
  (defvar elpaca-repos-directory (expand-file-name "repos/" elpaca-directory))
  (defvar elpaca-order '(elpaca :repo "https://github.com/progfolio/elpaca.git"
				:ref nil
				:files (:defaults "elpaca-test.el" (:exclude "extensions"))
				:build (:not elpaca--activate-package)))
  (let* ((repo  (expand-file-name "elpaca/" elpaca-repos-directory))
	 (build (expand-file-name "elpaca/" elpaca-builds-directory))
	 (order (cdr elpaca-order))
	 (default-directory repo))
    (add-to-list 'load-path (if (file-exists-p build) build repo))
    (unless (file-exists-p repo)
      (make-directory repo t)
      (when (< emacs-major-version 28) (require 'subr-x))
      (condition-case-unless-debug err
	  (if-let ((buffer (pop-to-buffer-same-window "*elpaca-bootstrap*"))
		   ((zerop (call-process "git" nil buffer t "clone"
					 (plist-get order :repo) repo)))
		   ((zerop (call-process "git" nil buffer t "checkout"
					 (or (plist-get order :ref) "--"))))
		   (emacs (concat invocation-directory invocation-name))
		   ((zerop (call-process emacs nil buffer nil "-Q" "-L" "." "--batch"
					 "--eval" "(byte-recompile-directory \".\" 0 'force)")))
		   ((require 'elpaca))
		   ((elpaca-generate-autoloads "elpaca" repo)))
	      (progn (message "%s" (buffer-string)) (kill-buffer buffer))
	    (error "%s" (with-current-buffer buffer (buffer-string))))
	((error) (warn "%s" err) (delete-directory repo 'recursive))))
    (unless (require 'elpaca-autoloads nil t)
      (require 'elpaca)
      (elpaca-generate-autoloads "elpaca" repo)
      (load "./elpaca-autoloads")))
  (add-hook 'after-init-hook #'elpaca-process-queues)
  (elpaca `(,@elpaca-order))
#+end_src
#+begin_src elisp :tangle early-init.el
  (setq package-enable-at-startup nil)
#+end_src
#+begin_src elisp :tangle init.el
  ;; Install use-package support
  (elpaca elpaca-use-package
	  ;; Enable :elpaca use-package keyword.
	  (elpaca-use-package-mode)
	  ;; Assume :elpaca t unless otherwise specified.
	  (setq elpaca-use-package-by-default t))

  ;; Block until current queue processed.
  (elpaca-wait)
#+end_src
** Install Magit
#+begin_src elisp :tangle init.el
  (use-package magit
    :config
    ;; Refresh the status buffer of the current repository after a buffer is saved to its file.
    (add-hook 'after-save-hook 'magit-after-save-refresh-status t))
#+end_src
** Install Diff-Hl-Mode
[[https://github.com/dgutov/diff-hl][Diff-Hl-Mode]] highlights uncommitted changes on the left side of the
window, allows to jump between and revert them selectively.
#+begin_src elisp :tangle init.el
  (use-package diff-hl
    :hook
    ((org-mode prog-mode) . diff-hl-mode)
    (magit-pre-refresh-hook . diff-hl-magit-pre-refresh)
    (magit-post-refresh . diff-hl-magit-post-refresh)
    :config
    ;; Perform highlighting on-the-fly.
    (diff-hl-flydiff-mode 1))
#+end_src
** Load support for language on execution of code block
#+begin_src elisp :tangle init.el
  (defadvice org-babel-execute-src-block (around load-language nil activate)
    "Load language if needed"
    (let ((language (org-element-property :language (org-element-at-point))))
      (unless (cdr (assoc (intern language) org-babel-load-languages))
	(add-to-list 'org-babel-load-languages (cons (intern language) t))
	(org-babel-do-load-languages 'org-babel-load-languages org-babel-load-languages))
      ad-do-it))
#+end_src
Source: https://emacs.stackexchange.com/a/20618
** Ensure environment variables look the same as in the user's shell
#+begin_src elisp :tangle init.el
  (use-package exec-path-from-shell
    :config
    (exec-path-from-shell-initialize))
#+end_src
** Remember recently edited files
#+begin_src elisp :tangle init.el
  (recentf-mode 1)
#+end_src
** Remember minibuffer prompt history
#+begin_src elisp :tangle init.el
  (savehist-mode 1)
#+end_src
** Prevent using UI dialogs for prompts
#+begin_src elisp :tangle init.el
  (setq use-dialog-box nil)
#+end_src
** Always use `y` or `n` for yes-no responses
#+begin_src elisp :tangle init.el
  (defalias 'yes-or-no-p 'y-or-n-p)
#+end_src
** Automatically revert buffers for changed files
#+begin_src elisp :tangle init.el
  (global-auto-revert-mode 1)
#+end_src
** Automatically revert changed file buffers and custom bufffers
#+begin_src elisp :tangle init.el
  (setq global-auto-revert-non-file-buffers 1)
#+end_src
** Make ~Auto-Revert-Mode~ perform checks every half a second
#+begin_src elisp :tangle init.el
  (setq auto-revert-interval 0.5)
#+end_src
** Install Vertico
#+begin_src elisp :tangle init.el
  (use-package vertico
    :config
    (vertico-mode)
    (vertico-reverse-mode))
#+end_src
** Install Orderless
#+begin_src elisp :tangle init.el
  (use-package orderless
    :custom
    (completion-styles '(orderless basic))
    (completion-category-overrides '((file (styles basic partial-completion)))))
#+end_src
** Enable ~pixel-scroll-precision-mode~ if present
#+begin_src elisp :tangle init.el
  (when (fboundp 'pixel-scroll-precision-mode)
    (pixel-scroll-precision-mode 1))
#+end_src
** Typed text replaces the active selection
#+begin_src elisp :tangle init.el
  (delete-selection-mode 1)
#+end_src
** Make the cursor a thin bar
#+begin_src elisp :tangle init.el
  (setq-default cursor-type 'bar)
#+end_src
** Disable the tool bar
#+begin_src elisp :tangle init.el
  (tool-bar-mode -1)
#+end_src
** Disable the menu bar
#+begin_src elisp :tangle init.el
  (menu-bar-mode -1)
#+end_src
** Automatically save place in each file
#+begin_src elisp :tangle init.el
  (save-place-mode 1)
#+end_src
** Install undo-tree
#+begin_src elisp :tangle init.el
  (use-package undo-tree
    :config
    (global-undo-tree-mode 1)
    (setq undo-tree-history-directory-alist '(("." . "~/.emacs.d/undo"))))
#+end_src
** Make TAB intelligent
TAB first tries to indent the current line, and if the line was already indented, then try to complete the thing at point.
#+begin_src elisp :tangle init.el
  (setq tab-always-indent 'complete)
#+end_src
** Install Corfu
#+begin_src elisp :tangle init.el
  (use-package corfu
    :init
    (global-corfu-mode 1)
    :custom
    (completion-cycle-threshold 3))
#+end_src
** Make the mode line face inherit ~variable-pitch~
#+begin_src elisp :tangle init.el
  (set-face-attribute 'mode-line nil :inherit 'variable-pitch)
#+end_src
** Make the fringe white
#+begin_src elisp :tangle init.el
  (set-face-attribute 'fringe nil :background "white")
#+end_src
** Flash the Emacs mode line instead of ringing the bell
#+begin_src elisp :tangle init.el
  (use-package mode-line-bell
    :config
    (mode-line-bell-mode 1))
#+end_src
** In Termux open URLs using default method
#+begin_src elisp :tangle init.el
  (when (getenv "TERMUX_VERSION")
    (setq browse-url-browser-function 'browse-url-xdg-open))
#+end_src
** Configure Org-Mode
#+begin_src elisp :tangle init.el
  (use-package org
    :elpaca nil
    :bind (("C-c l" . org-store-link))
    :hook ((org-mode . variable-pitch-mode)
	   (org-mode . visual-line-mode))
    :custom
    (org-attach-store-link-p 'attached)
    (org-id-link-to-org-use-id t)
    :config
    (set-face-attribute 'org-block nil :inherit 'fixed-pitch))
#+end_src
** Install Which-Key-Mode
#+begin_src elisp :tangle init.el
  (use-package which-key
    :config
    (which-key-mode 1))
#+end_src
** Install Consult
#+begin_src elisp :tangle init.el
  (use-package consult
    :bind ((;; C-c bindings in `mode-specific-map'
	    ("C-c M-x" . consult-mode-command)
	    ("C-c h" . consult-history)
	    ("C-c k" . consult-kmacro)
	    ("C-c m" . consult-man)
	    ("C-c i" . consult-info)
	    ([remap Info-search] . consult-info)
	    ;; C-x bindings in `ctl-x-map'
	    ("C-x M-:" . consult-complex-command)     ;; orig. repeat-complex-command
	    ("C-x b" . consult-buffer)                ;; orig. switch-to-buffer
	    ("C-x 4 b" . consult-buffer-other-window) ;; orig. switch-to-buffer-other-window
	    ("C-x 5 b" . consult-buffer-other-frame)  ;; orig. switch-to-buffer-other-frame
	    ("C-x t b" . consult-buffer-other-tab)    ;; orig. switch-to-buffer-other-tab
	    ("C-x r b" . consult-bookmark)            ;; orig. bookmark-jump
	    ("C-x p b" . consult-project-buffer)      ;; orig. project-switch-to-buffer
	    ;; Custom M-# bindings for fast register access
	    ("M-#" . consult-register-load)
	    ("M-'" . consult-register-store)          ;; orig. abbrev-prefix-mark (unrelated)
	    ("C-M-#" . consult-register)
	    ;; Other custom bindings
	    ("M-y" . consult-yank-pop)                ;; orig. yank-pop
	    ;; M-g bindings in `goto-map'
	    ("M-g e" . consult-compile-error)
	    ("M-g f" . consult-flymake)               ;; Alternative: consult-flycheck
	    ("M-g g" . consult-goto-line)             ;; orig. goto-line
	    ("M-g M-g" . consult-goto-line)           ;; orig. goto-line
	    ("M-g o" . consult-outline)               ;; Alternative: consult-org-heading
	    ("M-g m" . consult-mark)
	    ("M-g k" . consult-global-mark)
	    ("M-g i" . consult-imenu)
	    ("M-g I" . consult-imenu-multi)
	    ;; M-s bindings in `search-map'
	    ("M-s d" . consult-find)                  ;; Alternative: consult-fd
	    ("M-s c" . consult-locate)
	    ("M-s g" . consult-grep)
	    ("M-s G" . consult-git-grep)
	    ("M-s r" . consult-ripgrep)
	    ("M-s l" . consult-line)
	    ("M-s L" . consult-line-multi)
	    ("M-s k" . consult-keep-lines)
	    ("M-s u" . consult-focus-lines)
	    ;; Isearch integration
	    ("M-s e" . consult-isearch-history)
	    :map isearch-mode-map
	    ("M-e" . consult-isearch-history)         ;; orig. isearch-edit-string
	    ("M-s e" . consult-isearch-history)       ;; orig. isearch-edit-string
	    ("M-s l" . consult-line)                  ;; needed by consult-line to detect isearch
	    ("M-s L" . consult-line-multi)            ;; needed by consult-line to detect isearch
	    ;; Minibuffer history
	    :map minibuffer-local-map
	    ("M-s" . consult-history)                 ;; orig. next-matching-history-element
	    ("M-r" . consult-history))))
#+end_src
** Install Ace-Jump-Mode
#+begin_src elisp :tangle init.el
  (use-package ace-jump-mode
    :bind (("C-c SPC" . ace-jump-mode)))
#+end_src
* Android configuration
** The configuration script
:PROPERTIES:
:header-args: :tangle (if (getenv "TERMUX_VERSION") "no" "configure-termux") :results none 
:END:
*** Deliberately cause the configuration script to fail
#+begin_src shell
  set -euxo pipefail
#+end_src
*** Select mirror or mirror group
#+begin_src shell
  : "Did I select either a mirror or a mirror group?"
  if [ ! -f .termux-change-repo ]; then
      termux-change-repo
      touch .termux-change-repo
  fi
#+end_src
*** Update apt databases from configured repositories
We update apt databases at most once a week as suggested [[https://wiki.termux.com/wiki/Package_Management][here]].
#+begin_src shell
  : "Did I update the apt databases in the last week?"
  if [ ! -f .pkg-update ] || [[ $(find . -name ".pkg-update" -mtime +7 -print) ]]; then
      pkg update -y
      touch .pkg-update
  fi
#+end_src
References:
- https://stackoverflow.com/a/32019461
- https://wiki.termux.com/wiki/Package_Management
*** Upgrade all installed packages to the latest version
#+begin_src shell
  : "Did I upgrade all the installed packages?"
  if [ ! -f .pkg-upgrade ]; then
      pkg upgrade -y
      touch .pkg-upgrade
  fi
#+end_src
*** Enable the ~x11-repo~ repository
#+begin_src shell
  : "Did I enable the x11-repo repository?"
  if [ ! -f .x11-repo ]; then
      pkg install x11-repo
      touch .x11-repo
  fi
#+end_src
References:
- https://github.com/termux/termux-x11
*** Install the nighly companion package
#+begin_src shell
  : "Did I install the companion package?"
  if [ ! -f .pkg-install-termux-x11-nightly ]; then
      pkg install termux-x11-nightly -y
      touch .pkg-install-termux-x11-nightly
  fi
#+end_src
*** Install Git
#+begin_src shell
  : "Did I install Git?"
  if [ ! -f .pkg-install-git ]; then
      pkg install git -y
      touch .pkg-install-git
  fi
#+end_src
*** Install ~git-annex~
#+begin_src shell
  : "Did I install git-annex?"
  if [ ! -f .pkg-install-git-annex ]; then
      bash <(curl https://git-annex.branchable.com/install/Android/git-annex-install)
      echo "PATH='\$PATH:`pwd`/git-annex.linux'" >> .bash_profile
      touch .pkg-install-git-annex
  fi
#+end_src
*** Install Emacs
#+begin_src shell
  : "Did I install Emacs?"
  if [ ! -f .pkg-install-emacs ]; then
      pkg install emacs-x -y
      touch .pkg-install-emacs
  fi
#+end_src
*** Clone this repository
#+begin_src shell
  : "Did I clone the Emacs configuration repository?"
  if [ ! -d .emacs.d ]; then
      git clone https://github.com/gscatto/.emacs.d.git
  fi
#+end_src
*** Generate configuration update script
#+begin_src shell
  : "Did I generate the configuration update script?"
  if [ ! -f update-emacs-configuration ]; then
      echo "#!/usr/bin/env bash" > update-emacs-configuration
      echo "set -euxo pipefail" >> update-emacs-configuration
      echo "cd .emacs.d" >> update-emacs-configuration
      echo "git pull --ff-only" >> update-emacs-configuration
      echo "emacs --batch -Q -l org README.org -f org-babel-tangle" >> update-emacs-configuration
      echo "sv restart emacsd" >> update-emacs-configuration
      chmod +x update-emacs-configuration
  fi
#+end_src
*** Run the configuration update script for the first time
#+begin_src shell
  : "Generate the Emacs configuration"
  ./update-emacs-configuration
#+end_src
*** Set the ~EMACS_SOCKET_NAME~ environment variable
#+begin_src shell
  : "Did I set the EMACS_SOCKET_NAME environment variable?"
  if ! grep -q "export EMACS_SOCKET_NAME=" .bash_profile; then
      echo "export EMACS_SOCKET_NAME=\"$(emacs -Q --batch -l server --eval '(princ (concat server-socket-dir "/server"))')\"" >> .bash_profile
  fi
#+end_src
*** Install ~termux-services~ package
#+begin_src shell
  : "Did I install termux-services package?"
  if [ ! -f .pkg-install-termux-services ]; then
      pkg install termux-services -y
      touch .pkg-install-termux-services
      : "Restart Termux so that the service-daemon is started"
      exit
  fi
#+end_src
References:
- https://wiki.archlinux.org/title/environment_variables
*** Enable and run the Emacs daemon service
#+begin_src shell
  : "Did I enable and run the Emacs daemon service?"
  if [ ! -f .sv-enable-emacsd ]; then
      sv-enable emacsd
      touch .sv-enable-emacsd
  fi
#+end_src
References:
- https://wiki.termux.com/wiki/Termux-services
** Remote configuration process
*** Send the configuration script to the terminal
#+begin_src shell :results silent
  cat configure-termux | curl -T - https://ppng.io/kj1q98cnj12
#+end_src
*** Receive and execute the configuration script at the terminal
#+begin_src shell :results none
  bash <(curl https://ppng.io/kj1q98cnj12)
#+end_src
